repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2  # Match your ruff version from pyproject.toml
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Use same version as in pyproject.toml
    hooks:
      - id: mypy
        additional_dependencies:
          - types-setuptools
          - types-requests
          - types-sqlalchemy
          - types-PyYAML
          - types-python-dateutil
          - pyarrow-stubs>=17.0.0
          - dagster>=1.7.8
          - sqlmesh<1.0
          - pytest>=8.3.2
          - pyarrow>=18.0.0

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.2  # Latest stable version
    hooks:
      - id: uv-lock
        name: Lock dependencies
        args: ["--python", "3.11"]
        files: ^pyproject\.toml$ 