repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2  # Match your ruff version from pyproject.toml
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        require_serial: true
        additional_dependencies: []  # All dependencies are in our venv

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.2  # Latest stable version
    hooks:
      - id: uv-lock
        name: Lock dependencies
        args: ["--python", "3.11"]
        files: ^pyproject\.toml$ 